<?php

namespace Database\Seeders;

use App\Models\Borrowing;
use App\Models\User;
use App\Models\Book;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Str;

class BorrowingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get users (exclude admin)
        $users = User::where('role', 'siswa')->get();
        $books = Book::all();

        if ($users->isEmpty() || $books->isEmpty()) {
            $this->command->warn('No users or books found. Please run UserSeeder and BookSeeder first.');
            return;
        }

        $borrowingsData = [
            // Active borrowings (currently borrowed)
            [
                'user_index' => 0,
                'book_index' => 0,
                'borrow_date' => Carbon::now()->subDays(5),
                'due_date' => Carbon::now()->addDays(9),
                'return_date' => null,
                'status' => 'Dipinjam',
                'denda' => 0,
                'notes' => null,
            ],
            [
                'user_index' => 1,
                'book_index' => 1,
                'borrow_date' => Carbon::now()->subDays(3),
                'due_date' => Carbon::now()->addDays(11),
                'return_date' => null,
                'status' => 'Dipinjam',
                'denda' => 0,
                'notes' => null,
            ],
            [
                'user_index' => 2,
                'book_index' => 2,
                'borrow_date' => Carbon::now()->subDays(10),
                'due_date' => Carbon::now()->addDays(4),
                'return_date' => null,
                'status' => 'Dipinjam',
                'denda' => 0,
                'notes' => null,
            ],
            // Overdue borrowing
            [
                'user_index' => 3,
                'book_index' => 3,
                'borrow_date' => Carbon::now()->subDays(20),
                'due_date' => Carbon::now()->subDays(6),
                'return_date' => null,
                'status' => 'Terlambat',
                'denda' => 15000,
                'notes' => 'Terlambat 6 hari',
            ],
            [
                'user_index' => 2,
                'book_index' => 3,
                'borrow_date' => Carbon::now()->subDays(15),
                'due_date' => Carbon::now()->subDays(1),
                'return_date' => null,
                'status' => 'Terlambat',
                'denda' => 15000,
                'notes' => 'Terlambat 1 hari',
            ],
            // Returned borrowings - Juli 2025
            [
                'user_index' => 3,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 7, 5),
                'due_date' => Carbon::create(2025, 7, 19),
                'return_date' => Carbon::create(2025, 7, 18),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 7, 7),
                'due_date' => Carbon::create(2025, 7, 21),
                'return_date' => Carbon::create(2025, 7, 23),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 5,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 7, 8),
                'due_date' => Carbon::create(2025, 7, 22),
                'return_date' => Carbon::create(2025, 7, 20),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 5,
                'borrow_date' => Carbon::create(2025, 7, 9),
                'due_date' => Carbon::create(2025, 7, 23),
                'return_date' => Carbon::create(2025, 7, 21),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 6,
                'borrow_date' => Carbon::create(2025, 7, 11),
                'due_date' => Carbon::create(2025, 7, 25),
                'return_date' => Carbon::create(2025, 7, 24),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 7,
                'borrow_date' => Carbon::create(2025, 7, 12),
                'due_date' => Carbon::create(2025, 7, 26),
                'return_date' => Carbon::create(2025, 7, 25),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 8,
                'borrow_date' => Carbon::create(2025, 7, 14),
                'due_date' => Carbon::create(2025, 7, 28),
                'return_date' => Carbon::create(2025, 7, 27),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 0,
                'borrow_date' => Carbon::create(2025, 7, 15),
                'due_date' => Carbon::create(2025, 7, 29),
                'return_date' => Carbon::create(2025, 7, 28),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 7, 16),
                'due_date' => Carbon::create(2025, 7, 30),
                'return_date' => Carbon::create(2025, 7, 29),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 7, 17),
                'due_date' => Carbon::create(2025, 7, 31),
                'return_date' => Carbon::create(2025, 7, 30),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 7, 18),
                'due_date' => Carbon::create(2025, 8, 1),
                'return_date' => Carbon::create(2025, 7, 31),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 7, 19),
                'due_date' => Carbon::create(2025, 8, 2),
                'return_date' => Carbon::create(2025, 8, 1),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 5,
                'borrow_date' => Carbon::create(2025, 7, 20),
                'due_date' => Carbon::create(2025, 8, 3),
                'return_date' => Carbon::create(2025, 8, 5),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 4,
                'book_index' => 6,
                'borrow_date' => Carbon::create(2025, 7, 21),
                'due_date' => Carbon::create(2025, 8, 4),
                'return_date' => Carbon::create(2025, 8, 3),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 7,
                'borrow_date' => Carbon::create(2025, 7, 22),
                'due_date' => Carbon::create(2025, 8, 5),
                'return_date' => Carbon::create(2025, 8, 4),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 8,
                'borrow_date' => Carbon::create(2025, 7, 23),
                'due_date' => Carbon::create(2025, 8, 6),
                'return_date' => Carbon::create(2025, 8, 5),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 0,
                'borrow_date' => Carbon::create(2025, 7, 24),
                'due_date' => Carbon::create(2025, 8, 7),
                'return_date' => Carbon::create(2025, 8, 6),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 7, 25),
                'due_date' => Carbon::create(2025, 8, 8),
                'return_date' => Carbon::create(2025, 8, 7),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 7, 26),
                'due_date' => Carbon::create(2025, 8, 9),
                'return_date' => Carbon::create(2025, 8, 8),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 7, 27),
                'due_date' => Carbon::create(2025, 8, 10),
                'return_date' => Carbon::create(2025, 8, 9),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 7, 28),
                'due_date' => Carbon::create(2025, 8, 11),
                'return_date' => Carbon::create(2025, 8, 13),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            // Agustus 2025
            [
                'user_index' => 3,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 8, 12),
                'due_date' => Carbon::create(2025, 8, 26),
                'return_date' => Carbon::create(2025, 8, 28),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 0,
                'book_index' => 0,
                'borrow_date' => Carbon::create(2025, 8, 1),
                'due_date' => Carbon::create(2025, 8, 15),
                'return_date' => Carbon::create(2025, 8, 14),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 8, 3),
                'due_date' => Carbon::create(2025, 8, 17),
                'return_date' => Carbon::create(2025, 8, 16),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 6,
                'borrow_date' => Carbon::create(2025, 8, 6),
                'due_date' => Carbon::create(2025, 8, 20),
                'return_date' => Carbon::create(2025, 8, 19),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 8,
                'borrow_date' => Carbon::create(2025, 8, 8),
                'due_date' => Carbon::create(2025, 8, 22),
                'return_date' => Carbon::create(2025, 8, 21),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 8, 10),
                'due_date' => Carbon::create(2025, 8, 24),
                'return_date' => Carbon::create(2025, 8, 23),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 8, 14),
                'due_date' => Carbon::create(2025, 8, 28),
                'return_date' => Carbon::create(2025, 8, 27),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 6,
                'borrow_date' => Carbon::create(2025, 8, 16),
                'due_date' => Carbon::create(2025, 8, 30),
                'return_date' => Carbon::create(2025, 8, 29),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 8,
                'borrow_date' => Carbon::create(2025, 8, 18),
                'due_date' => Carbon::create(2025, 9, 1),
                'return_date' => Carbon::create(2025, 8, 31),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 8, 20),
                'due_date' => Carbon::create(2025, 9, 3),
                'return_date' => Carbon::create(2025, 9, 2),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 8, 21),
                'due_date' => Carbon::create(2025, 9, 4),
                'return_date' => Carbon::create(2025, 9, 6),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 3,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 8, 22),
                'due_date' => Carbon::create(2025, 9, 5),
                'return_date' => Carbon::create(2025, 9, 4),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 8, 23),
                'due_date' => Carbon::create(2025, 9, 6),
                'return_date' => Carbon::create(2025, 9, 5),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 5,
                'borrow_date' => Carbon::create(2025, 8, 24),
                'due_date' => Carbon::create(2025, 9, 7),
                'return_date' => Carbon::create(2025, 9, 6),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            // September 2025
            [
                'user_index' => 3,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 9, 4),
                'due_date' => Carbon::create(2025, 9, 18),
                'return_date' => Carbon::create(2025, 9, 17),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 9, 5),
                'due_date' => Carbon::create(2025, 9, 19),
                'return_date' => Carbon::create(2025, 9, 18),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 9, 6),
                'due_date' => Carbon::create(2025, 9, 20),
                'return_date' => Carbon::create(2025, 9, 19),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 7,
                'borrow_date' => Carbon::create(2025, 9, 7),
                'due_date' => Carbon::create(2025, 9, 21),
                'return_date' => Carbon::create(2025, 9, 20),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 8,
                'borrow_date' => Carbon::create(2025, 9, 8),
                'due_date' => Carbon::create(2025, 9, 22),
                'return_date' => Carbon::create(2025, 9, 21),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 0,
                'borrow_date' => Carbon::create(2025, 9, 9),
                'due_date' => Carbon::create(2025, 9, 23),
                'return_date' => Carbon::create(2025, 9, 22),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 9, 10),
                'due_date' => Carbon::create(2025, 9, 24),
                'return_date' => Carbon::create(2025, 9, 26),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 5,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 9, 11),
                'due_date' => Carbon::create(2025, 9, 25),
                'return_date' => Carbon::create(2025, 9, 24),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 9, 12),
                'due_date' => Carbon::create(2025, 9, 26),
                'return_date' => Carbon::create(2025, 9, 25),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 9, 13),
                'due_date' => Carbon::create(2025, 9, 27),
                'return_date' => Carbon::create(2025, 9, 26),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 5,
                'borrow_date' => Carbon::create(2025, 9, 14),
                'due_date' => Carbon::create(2025, 9, 28),
                'return_date' => Carbon::create(2025, 9, 30),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 3,
                'book_index' => 6,
                'borrow_date' => Carbon::create(2025, 9, 16),
                'due_date' => Carbon::create(2025, 9, 30),
                'return_date' => Carbon::create(2025, 9, 29),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 7,
                'borrow_date' => Carbon::create(2025, 9, 17),
                'due_date' => Carbon::create(2025, 10, 1),
                'return_date' => Carbon::create(2025, 9, 30),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 8,
                'borrow_date' => Carbon::create(2025, 9, 18),
                'due_date' => Carbon::create(2025, 10, 2),
                'return_date' => Carbon::create(2025, 10, 1),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 0,
                'borrow_date' => Carbon::create(2025, 9, 19),
                'due_date' => Carbon::create(2025, 10, 3),
                'return_date' => Carbon::create(2025, 10, 2),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 9, 20),
                'due_date' => Carbon::create(2025, 10, 4),
                'return_date' => Carbon::create(2025, 10, 3),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 9, 21),
                'due_date' => Carbon::create(2025, 10, 5),
                'return_date' => Carbon::create(2025, 10, 4),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 9, 22),
                'due_date' => Carbon::create(2025, 10, 6),
                'return_date' => Carbon::create(2025, 10, 5),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            // Oktober 2025
            [
                'user_index' => 1,
                'book_index' => 6,
                'borrow_date' => Carbon::create(2025, 10, 7),
                'due_date' => Carbon::create(2025, 10, 21),
                'return_date' => Carbon::create(2025, 10, 20),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 8,
                'borrow_date' => Carbon::create(2025, 10, 8),
                'due_date' => Carbon::create(2025, 10, 22),
                'return_date' => Carbon::create(2025, 10, 24),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 3,
                'book_index' => 0,
                'borrow_date' => Carbon::create(2025, 10, 9),
                'due_date' => Carbon::create(2025, 10, 23),
                'return_date' => Carbon::create(2025, 10, 22),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 10, 10),
                'due_date' => Carbon::create(2025, 10, 24),
                'return_date' => Carbon::create(2025, 10, 23),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 10, 11),
                'due_date' => Carbon::create(2025, 10, 25),
                'return_date' => Carbon::create(2025, 10, 24),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 10, 12),
                'due_date' => Carbon::create(2025, 10, 26),
                'return_date' => Carbon::create(2025, 10, 25),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 10, 13),
                'due_date' => Carbon::create(2025, 10, 27),
                'return_date' => Carbon::create(2025, 10, 29),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 2,
                'book_index' => 5,
                'borrow_date' => Carbon::create(2025, 10, 14),
                'due_date' => Carbon::create(2025, 10, 28),
                'return_date' => Carbon::create(2025, 10, 27),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 6,
                'borrow_date' => Carbon::create(2025, 10, 15),
                'due_date' => Carbon::create(2025, 10, 29),
                'return_date' => Carbon::create(2025, 10, 28),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 7,
                'borrow_date' => Carbon::create(2025, 10, 16),
                'due_date' => Carbon::create(2025, 10, 30),
                'return_date' => Carbon::create(2025, 10, 29),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 8,
                'borrow_date' => Carbon::create(2025, 10, 17),
                'due_date' => Carbon::create(2025, 10, 31),
                'return_date' => Carbon::create(2025, 10, 30),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 0,
                'borrow_date' => Carbon::create(2025, 10, 19),
                'due_date' => Carbon::create(2025, 11, 2),
                'return_date' => Carbon::create(2025, 11, 1),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 10, 20),
                'due_date' => Carbon::create(2025, 11, 3),
                'return_date' => Carbon::create(2025, 11, 5),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 2,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 10, 21),
                'due_date' => Carbon::create(2025, 11, 4),
                'return_date' => Carbon::create(2025, 11, 3),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 10, 22),
                'due_date' => Carbon::create(2025, 11, 5),
                'return_date' => Carbon::create(2025, 11, 4),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            // November 2025
            [
                'user_index' => 1,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 11, 2),
                'due_date' => Carbon::create(2025, 11, 16),
                'return_date' => Carbon::create(2025, 11, 15),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 11, 3),
                'due_date' => Carbon::create(2025, 11, 17),
                'return_date' => Carbon::create(2025, 11, 19),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 5,
                'book_index' => 5,
                'borrow_date' => Carbon::create(2025, 11, 4),
                'due_date' => Carbon::create(2025, 11, 18),
                'return_date' => Carbon::create(2025, 11, 17),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 6,
                'borrow_date' => Carbon::create(2025, 11, 6),
                'due_date' => Carbon::create(2025, 11, 20),
                'return_date' => Carbon::create(2025, 11, 19),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 7,
                'borrow_date' => Carbon::create(2025, 11, 7),
                'due_date' => Carbon::create(2025, 11, 21),
                'return_date' => Carbon::create(2025, 11, 20),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 8,
                'borrow_date' => Carbon::create(2025, 11, 8),
                'due_date' => Carbon::create(2025, 11, 22),
                'return_date' => Carbon::create(2025, 11, 21),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 0,
                'borrow_date' => Carbon::create(2025, 11, 9),
                'due_date' => Carbon::create(2025, 11, 23),
                'return_date' => Carbon::create(2025, 11, 25),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 4,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 11, 10),
                'due_date' => Carbon::create(2025, 11, 24),
                'return_date' => Carbon::create(2025, 11, 23),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 11, 11),
                'due_date' => Carbon::create(2025, 11, 25),
                'return_date' => Carbon::create(2025, 11, 24),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 11, 13),
                'due_date' => Carbon::create(2025, 11, 27),
                'return_date' => Carbon::create(2025, 11, 26),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 5,
                'borrow_date' => Carbon::create(2025, 11, 14),
                'due_date' => Carbon::create(2025, 11, 28),
                'return_date' => Carbon::create(2025, 11, 30),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 2,
                'book_index' => 6,
                'borrow_date' => Carbon::create(2025, 11, 15),
                'due_date' => Carbon::create(2025, 11, 29),
                'return_date' => Carbon::create(2025, 11, 28),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 7,
                'borrow_date' => Carbon::create(2025, 11, 16),
                'due_date' => Carbon::create(2025, 11, 30),
                'return_date' => Carbon::create(2025, 11, 29),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 8,
                'borrow_date' => Carbon::create(2025, 11, 17),
                'due_date' => Carbon::create(2025, 12, 1),
                'return_date' => Carbon::create(2025, 11, 30),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 0,
                'borrow_date' => Carbon::create(2025, 11, 18),
                'due_date' => Carbon::create(2025, 12, 2),
                'return_date' => Carbon::create(2025, 12, 1),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 11, 19),
                'due_date' => Carbon::create(2025, 12, 3),
                'return_date' => Carbon::create(2025, 12, 5),
                'status' => 'Dikembalikan',
                'denda' => 5000,
                'notes' => 'Terlambat 2 hari',
            ],
            [
                'user_index' => 1,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 11, 20),
                'due_date' => Carbon::create(2025, 12, 4),
                'return_date' => Carbon::create(2025, 12, 3),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 11, 21),
                'due_date' => Carbon::create(2025, 12, 5),
                'return_date' => Carbon::create(2025, 12, 4),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 11, 22),
                'due_date' => Carbon::create(2025, 12, 6),
                'return_date' => Carbon::create(2025, 12, 5),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            // Desember 2025
            [
                'user_index' => 0,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 12, 1),
                'due_date' => Carbon::create(2025, 12, 15),
                'return_date' => Carbon::create(2025, 12, 13),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 12, 10),
                'due_date' => Carbon::create(2025, 12, 24),
                'return_date' => Carbon::create(2025, 12, 22),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 0,
                'borrow_date' => Carbon::create(2025, 12, 2),
                'due_date' => Carbon::create(2025, 12, 16),
                'return_date' => Carbon::create(2025, 12, 15),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 12, 3),
                'due_date' => Carbon::create(2025, 12, 17),
                'return_date' => Carbon::create(2025, 12, 16),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 12, 4),
                'due_date' => Carbon::create(2025, 12, 18),
                'return_date' => Carbon::create(2025, 12, 17),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 5,
                'borrow_date' => Carbon::create(2025, 12, 5),
                'due_date' => Carbon::create(2025, 12, 19),
                'return_date' => Carbon::create(2025, 12, 18),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 6,
                'borrow_date' => Carbon::create(2025, 12, 6),
                'due_date' => Carbon::create(2025, 12, 20),
                'return_date' => Carbon::create(2025, 12, 19),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 7,
                'borrow_date' => Carbon::create(2025, 12, 7),
                'due_date' => Carbon::create(2025, 12, 21),
                'return_date' => Carbon::create(2025, 12, 20),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 8,
                'borrow_date' => Carbon::create(2025, 12, 8),
                'due_date' => Carbon::create(2025, 12, 22),
                'return_date' => Carbon::create(2025, 12, 21),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 0,
                'borrow_date' => Carbon::create(2025, 12, 9),
                'due_date' => Carbon::create(2025, 12, 23),
                'return_date' => Carbon::create(2025, 12, 22),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 1,
                'borrow_date' => Carbon::create(2025, 12, 11),
                'due_date' => Carbon::create(2025, 12, 25),
                'return_date' => Carbon::create(2025, 12, 24),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 5,
                'book_index' => 2,
                'borrow_date' => Carbon::create(2025, 12, 12),
                'due_date' => Carbon::create(2025, 12, 26),
                'return_date' => Carbon::create(2025, 12, 25),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 0,
                'book_index' => 3,
                'borrow_date' => Carbon::create(2025, 12, 13),
                'due_date' => Carbon::create(2025, 12, 27),
                'return_date' => Carbon::create(2025, 12, 26),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 1,
                'book_index' => 4,
                'borrow_date' => Carbon::create(2025, 12, 14),
                'due_date' => Carbon::create(2025, 12, 28),
                'return_date' => Carbon::create(2025, 12, 27),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 2,
                'book_index' => 5,
                'borrow_date' => Carbon::create(2025, 12, 15),
                'due_date' => Carbon::create(2025, 12, 29),
                'return_date' => Carbon::create(2025, 12, 28),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 3,
                'book_index' => 6,
                'borrow_date' => Carbon::create(2025, 12, 16),
                'due_date' => Carbon::create(2025, 12, 30),
                'return_date' => Carbon::create(2025, 12, 29),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            [
                'user_index' => 4,
                'book_index' => 7,
                'borrow_date' => Carbon::create(2025, 12, 17),
                'due_date' => Carbon::create(2025, 12, 31),
                'return_date' => Carbon::create(2025, 12, 30),
                'status' => 'Dikembalikan',
                'denda' => 0,
                'notes' => 'Dikembalikan tepat waktu',
            ],
            // Pending borrowing request
            [
                'user_index' => 5,
                'book_index' => 6,
                'borrow_date' => Carbon::now(),
                'due_date' => Carbon::now()->addDays(14),
                'return_date' => null,
                'status' => 'Pending',
                'denda' => 0,
                'notes' => 'Menunggu persetujuan admin',
            ],
        ];

        foreach ($borrowingsData as $data) {
            $userIndex = $data['user_index'] % $users->count();
            $bookIndex = $data['book_index'] % $books->count();
            $borrowId = Str::uuid();

            Borrowing::create([
                'id' => $borrowId,
                'user_id' => $users[$userIndex]->id,
                'book_id' => $books[$bookIndex]->id,
                'borrow_date' => $data['borrow_date']->format('Y-m-d'),
                'due_date' => $data['due_date']->format('Y-m-d'),
                'return_date' => $data['return_date']?->format('Y-m-d'),
                'status' => $data['status'],
                'denda' => $data['denda'],
                'notes' => $data['notes'],
            ]);

            // Update book stock if currently borrowed
            if (in_array($data['status'], ['Dipinjam', 'Terlambat', 'Tenggat'])) {
                $book = $books[$bookIndex];
                if ($book->stok > 0) {
                    $book->stok -= 1;
                    if ($book->stok === 0) {
                        $book->status = 'unavailable';
                    }
                    $book->save();
                }
            }
        }

        $this->command->info('Borrowings seeded successfully: ' . count($borrowingsData) . ' records created.');
    }
}
